name: Portfolio
title: Portfolio Damien D.
description: Portfolio de Damien D.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: "&Agrave; propos"
    url: /about
  - title: Contact
    url: /contact
  #- title: Feed
  #  url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
